package com.ansgar.rdroidpc.constants

import java.awt.event.KeyEvent

enum class AdbKeyCode(val keyCode: Int, val equalKeyEvent: Int? = null, val isChar: Boolean) {
    KEYCODE_UNKNOWN(0, null, false),
    KEYCODE_MEN(1, null, false),
    KEYCODE_SOFT_RIGH(2, null, false),
    KEYCODE_HOME(3, null, false),
    KEYCODE_BACK(4, null, false),
    KEYCODE_CAL(5, null, false),
    KEYCODE_END_CALL(6, null, false),
    KEYCODE_0(7, KeyEvent.VK_0, true),
    KEYCODE_1(8, KeyEvent.VK_1, true),
    KEYCODE_2(9, KeyEvent.VK_2, true),
    KEYCODE_3(10, KeyEvent.VK_3, true),
    KEYCODE_4(11, KeyEvent.VK_4, true),
    KEYCODE_5(12, KeyEvent.VK_5, true),
    KEYCODE_6(13, KeyEvent.VK_6, true),
    KEYCODE_7(14, KeyEvent.VK_7, true),
    KEYCODE_8(15, KeyEvent.VK_8, true),
    KEYCODE_9(16, KeyEvent.VK_9, true),
    KEYCODE_STAR(17, null, false),
    KEYCODE_POUND(18, null, false),
    KEYCODE_DPAD_UP(19, KeyEvent.VK_UP, false),
    KEYCODE_DPAD_DOWN(20, KeyEvent.VK_DOWN, false),
    KEYCODE_DPAD_LEFT(21, KeyEvent.VK_LEFT, false),
    KEYCODE_DPAD_RIGHT(22, KeyEvent.VK_RIGHT, false),
    KEYCODE_DPAD_CENTER(23, null, false),
    KEYCODE_VOLUME_UP(24, null, false),
    KEYCODE_VOLUME_DOWN(25, null, false),
    KEYCODE_POWER(26, null, false),
    KEYCODE_CAMERA(27, null, false),
    KEYCODE_CLEAR(28, null, false),
    KEYCODE_A(29, KeyEvent.VK_A, true),
    KEYCODE_B(30, KeyEvent.VK_B, true),
    KEYCODE_C(31, KeyEvent.VK_C, true),
    KEYCODE_D(32, KeyEvent.VK_D, true),
    KEYCODE_E(33, KeyEvent.VK_E, true),
    KEYCODE_F(34, KeyEvent.VK_F, true),
    KEYCODE_G(35, KeyEvent.VK_G, true),
    KEYCODE_H(36, KeyEvent.VK_H, true),
    KEYCODE_I(37, KeyEvent.VK_I, true),
    KEYCODE_J(38, KeyEvent.VK_J, true),
    KEYCODE_K(39, KeyEvent.VK_K, true),
    KEYCODE_L(40, KeyEvent.VK_L, true),
    KEYCODE_M(41, KeyEvent.VK_M, true),
    KEYCODE_N(42, KeyEvent.VK_N, true),
    KEYCODE_O(43, KeyEvent.VK_O, true),
    KEYCODE_P(44, KeyEvent.VK_P, true),
    KEYCODE_Q(45, KeyEvent.VK_Q, true),
    KEYCODE_R(46, KeyEvent.VK_R, true),
    KEYCODE_S(47, KeyEvent.VK_S, true),
    KEYCODE_T(48, KeyEvent.VK_T, true),
    KEYCODE_U(49, KeyEvent.VK_U, true),
    KEYCODE_V(50, KeyEvent.VK_V, true),
    KEYCODE_W(51, KeyEvent.VK_W, true),
    KEYCODE_X(52, KeyEvent.VK_X, true),
    KEYCODE_Y(53, KeyEvent.VK_Y, true),
    KEYCODE_Z(54, KeyEvent.VK_Z, true),
    KEYCODE_COMMA(55, KeyEvent.VK_COMMA, false),
    KEYCODE_PERIOD(56, KeyEvent.VK_PERIOD, false),
    KEYCODE_ALT_LEFT(57, null, false),
    KEYCODE_ALT_RIGHT(58, null, false),
    KEYCODE_SHIFT_LEFT(59, null, false),
    KEYCODE_SHIFT_RIGHT(60, null, false),
    KEYCODE_TAB(61, KeyEvent.VK_TAB, false),
    KEYCODE_SPACE(62, KeyEvent.VK_SPACE, false),
    KEYCODE_SYM(63, null, false),
    KEYCODE_EXPLORER(64, null, false),
    KEYCODE_ENVELOPE(65, null, false),
    KEYCODE_ENTER(66, KeyEvent.VK_ENTER, false),
    KEYCODE_DEL(67, KeyEvent.VK_BACK_SPACE, false),
    KEYCODE_GRAVE(68, null, false),
    KEYCODE_MINUS(69, null, false),
    KEYCODE_EQUALS(70, null, false),
    KEYCODE_LEFT_BRACKET(71, KeyEvent.VK_OPEN_BRACKET, false),
    KEYCODE_RIGHT_BRACKET(72, KeyEvent.VK_CLOSE_BRACKET, false),
    KEYCODE_BACKSLASH(73, KeyEvent.VK_BACK_SLASH, false),
    KEYCODE_SEMICOLON(74, KeyEvent.VK_SEMICOLON, false),
    KEYCODE_APOSTROPHE(75, KeyEvent.VK_QUOTE, false),
    KEYCODE_SLASH(76, KeyEvent.VK_SLASH, false),
    KEYCODE_AT(77, null, false),
    KEYCODE_NUM(78, null, false),
    KEYCODE_HEADSETHOOK(79, null, false),
    KEYCODE_FOCUS(80, null, false),
    KEYCODE_PLUS(81, null, false),
    KEYCODE_MENU(82, null, false),
    KEYCODE_NOTIFICATION(83, null, false),
    KEYCODE_SEARCH(84, null, false),
    TAG_LAST_KEYCODE(85, null, false),
    KEYCODE_APP_SWITCH(187, null, false),
    KEYCODE_VOLUME_MUTE(164, null, false),
    KEYCODE_LANGUAGE_SWITCH(204, null, false);

    companion object {
        fun getAdbKeyEvent(e: KeyEvent?): AdbKeyCode {
            AdbKeyCode.values().forEach { adbKeyCode ->
                if (adbKeyCode.equalKeyEvent == e?.keyCode) return adbKeyCode
            }
            return KEYCODE_UNKNOWN
        }
    }
}